apiVersion: v1

kind: Service

metadata:

  name: secure-doc-service

  annotations:

    # This annotation tells AWS to create a Classic Load Balancer

    service.beta.kubernetes.io/aws-load-balancer-type: "clb"

spec:

  type: LoadBalancer

  selector:

    app: secure-doc

  ports:

    - protocol: TCP

      port: 80

      targetPort: 5000
